-- File auto generated by purescript-bridge! --
module Agora.Effect.GovernorMutation where

import Prelude

import Agora.Governor (GovernorDatum)
import Data.Generic.Rep (class Generic)
import Data.Lens (Iso', Lens', Prism', iso, prism')
import Data.Lens.Iso.Newtype (_Newtype)
import Data.Lens.Record (prop)
import Data.Maybe (Maybe(..))
import Data.Newtype (class Newtype)
import Plutus.V1.Ledger.Tx (TxOutRef)
import Type.Proxy (Proxy(Proxy))

newtype MutateGovernorDatum = MutateGovernorDatum
  { governorRef :: TxOutRef
  , newDatum :: GovernorDatum
  }

derive instance Generic MutateGovernorDatum _

derive instance Newtype MutateGovernorDatum _

--------------------------------------------------------------------------------

_MutateGovernorDatum :: Iso' MutateGovernorDatum {governorRef :: TxOutRef, newDatum :: GovernorDatum}
_MutateGovernorDatum = _Newtype
